---
openapi: 3.0.3
info:
  title: PROXIA-MES Monitoring-Dashboard Resource-Data Change-Event
  description: PROXIA-MES Monitoring-Dashboard Resource-Data Change-Event
  version: '1.0.0'
paths:
  "/dummy":
    get:
      summary: a dummy request for the generator
      responses:
        '200':
          description: OK
components:
  schemas:
    resource-change:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          nullable: true
        op:
          type: string
          enum:
            - 'c'
            - 'd'
            - 'u'