---
openapi: 3.0.3
info:
  title: PROXIA-MES COMU-Database Change-Events
  description: PROXIA-MES COMU-Database Change-Events
  version: '1.0.20'
paths:
  "/dummy":
    get:
      summary: a dummy request for the generator
      responses:
        '200':
          description: OK
components:
  schemas:
    #resource-statuses
    comuDbTrsResStatusChangeEvent:
      type: object
      properties: 
        before:
          $ref: '#/components/schemas/comuDbTrsResStatusColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsResStatusColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsResStatusColumns:
      type: object
      nullable: true
      properties:
        RES_STATUS_ID:
          type: string
        RES_STATUS_GRP_ID:
          type: string
        DISPLAYNAME:
          type: string
        RES_STATUS_COLOR:
          type: string
    comuDbTrsResStatusGrpChangeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrsResStatusGrpColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsResStatusGrpColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsResStatusGrpColumns:
      type: object
      nullable: true
      properties:
        RES_STATUS_GRP_ID:
          type: string
        RES_STATUS_MAINGRP_ID:
          type: string
        DISPLAYNAME:
          type: string
    comuDbTrsResStatusMainGrpChangeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrsResStatusMainGrpColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsResStatusMainGrpColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsResStatusMainGrpColumns:
      type: object
      nullable: true
      properties:
        RES_STATUS_MAINGRP_ID:
          type: string
        DISPLAYNAME:
          type: string
    #resources
    comuDbTrsResChangeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrsResColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsResColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsResColumns:
      type: object
      nullable: true
      properties:
        RES_ID:
          type: string
        PARENT_RES_ID:
          type: string
        PLANT_ID:
          type: string
        DISPLAYNAME:
          type: string
        RES_STATUS_ID:
          type: string
        RES_TYPE_ID:
          type: string
    comuDbTrsMachineEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrsMachineColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsMachineColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsMachineColumns:
      type: object
      nullable: true
      properties:
        RES_ID:
          type: string
        DESCRIPTION:
          type: string
        INVENTORY_NUMBER:
          type: string
        MANUFACTURER:
          type: string
        MACHINE_TYPE:
          type: string
        CONTROL_UNIT:
          type: string
        FACTORY_NR:
          type: string
    comuDbTrsPersEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrsPersColumns'
        after:
          $ref: '#/components/schemas/comuDbTrsPersColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrsPersColumns:
      type: object
      nullable: true
      properties:
        RES_ID:
          type: string
        LAST_NAME:
          type: string
        FIRST_NAME:
          type: string
        PERS_NR:
          type: string
        EMAIL:
          type: string
        HANDY_NR:
          type: string
    #orders
    comuDbTccCustomerEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTccCustomerColumns'
        after:
          $ref: '#/components/schemas/comuDbTccCustomerColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTccCustomerColumns:
      type: object
      nullable: true
      properties:
        CUSTOMER_ID:
          type: string
        DISPLAYNAME:
          type: string
    comuDbTsfCustOrderEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfCustOrderColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfCustOrderColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfCustOrderColumns:
      type: object
      nullable: true
      properties:
        CUST_ORDER_ID:
          type: string
        PLAN_LIEFERDATUM:
          type: string
          format: date-time          
        DISPLAYNAME:
          type: string
        CUST_ORDER_NR:
          type: string   
    comuDbTsfFaTypeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfFaTypeColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfFaTypeColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfFaTypeColumns:
      type: object
      nullable: true
      properties:
        FA_TYPE_ID:
          type: string
        DISPLAYNAME:
          type: string
    comuDbTsfFaEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfFaColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfFaColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfFaColumns:
      type: object
      nullable: true
      properties:
        FA_ID:
          type: string
        FA_TYPE_ID:
          type: string
        DISPLAYNAME:
          type: string
        PLANT_ID:
          type: string
        CUSTOMER_ID:
          type: string
        BEGIN_SCHEDULED:
          type: string
          format: date-time
          nullable: true
        END_SCHEDULED:
          type: string
          format: date-time
          nullable: true
        PLAN_LIEFERDATUM:
          type: string
          format: date-time
          nullable: true
        EARLIEST_BEGIN_TS:
          type: string
          format: date-time
          nullable: true
        DESIRED_DUE_TS:
          type: string
          format: date-time
          nullable: true
        FA_PRIORITY:
          type: number
          nullable: true
        FA_DESCRIPTION:
          type: string
        CUST_ORDER_ID:
          type: string
    comuDbTsfWtTypeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtTypeColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtTypeColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtTypeColumns:
      type: object
      nullable: true
      properties:
        WT_TYPE_ID:
          type: string
        DISPLAYNAME:
          type: string
    comuDbTsfWtStatusEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtStatusColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtStatusColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtStatusColumns:
      type: object
      nullable: true
      properties:
        WT_STATUS_ID:
          type: string
        DISPLAYNAME:
          type: string
    comuDbTsfWtEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtColumns:
      type: object
      nullable: true
      properties:
        WT_ID:
          type: string
        BEGIN_SCHEDULED:
          type: string
          format: date-time
        END_SCHEDULED:
          type: string
          format: date-time
        WT_STATUS_ID:
          type: string
        DISPLAYNAME:
          type: string
        PPS_ORDER:
          type: string
        PPS_ART_NR:
          type: string
        PPS_ART_DISPLAYNAME:
          type: string
        QTY_SOLL:
          type: number
          nullable: true
        PLANNED_SETUPTIME:
          type: number
          nullable: true
        PLANNED_PROCESSTIME:
          type: number
          nullable: true
        QTY_CONFIRMED_GUT:
          type: number
          nullable: true
        QTY_CONFIRMED_AUS:
          type: number
          nullable: true
        QTY_CONFIRMED_NACH:
          type: number
          nullable: true
        CONFIRMED_SETUPTIME:
          type: number
          nullable: true
        CONFIRMED_PROCESSTIME:
          type: number
          nullable: true
        WT_TYPE_ID:
          type: string
        FA_ID:
          type: string
        PLANT_ID:
          type: string
        EARLIEST_BEGIN_TS:
          type: string
          format: date-time
          nullable: true
        DESIRED_DUE_TS:
          type: string
          format: date-time
          nullable: true
    comuDbTsfWtQtyEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtQtyColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtQtyColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtQtyColumns:
      type: object
      nullable: true
      properties:
        WT_QTY_ID:
          type: string
        WT_ID:
          type: string
        RES_ID:
          type: string
        QTY_CLASS_ID:
          type: string
        QTY:
          type: number
    comuDbTsfWtZuordnungEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtZuordnungColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtZuordnungColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtZuordnungColumns:
      type: object
      nullable: true
      properties:
        WT_ID:
          type: string
        RES_ID:
          type: string
    comuDbTsfWtAnmeldungEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfWtAnmeldungColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfWtAnmeldungColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfWtAnmeldungColumns:
      type: object
      nullable: true
      properties:
        WT_ANMELDUNG_ID:
          type: string
        WT_ID:
          type: string
        RES_ID:
          type: string  
        WKPL_RES_ID:
          type: string
        BEGIN_TS:
          type: string
          format: date-time
        END_TS:
          type: string
          format: date-time
          nullable: true
    comuDbTsfResBelegungEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTsfResBelegungColumns'
        after:
          $ref: '#/components/schemas/comuDbTsfResBelegungColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTsfResBelegungColumns:
      type: object
      nullable: true
      properties:
        MASTER_RES_ID:
          type: string
        RES_ID:
          type: string
        BEGIN_TS:
          type: string
          format: date-time
        END_TS:
          type: string
          format: date-time
          nullable: true
    comuDbTrpOeeEvent:
      type: object
      properties:
        before:
          $ref: '#/components/schemas/comuDbTrpOeeColumns'
        after:
          $ref: '#/components/schemas/comuDbTrpOeeColumns'
        source:
          $ref: '#/components/schemas/source'
        op:
          $ref: '#/components/schemas/op'
        ts_ms:
          $ref: '#/components/schemas/ts_ms'
        transaction:
          $ref: '#/components/schemas/transaction'
    comuDbTrpOeeColumns:
      type: object
      nullable: true
      properties:
        RES_ID:
          type: string
        RES_DISPLAYNAME:
          type: string
          nullable: true
        SHIFT_ID:
          type: string
        CAL_DAY:
          type: string
          format: date-time
        LEISTUNG:
          type: number
          format: double
          nullable: true
        VERFUEGBARKEIT:
          type: number
          format: double
          nullable: true
        QUALITAET:
          type: number
          format: double
          nullable: true
        OEE:
          type: number
          format: double
          nullable: true
        WT_ANZAHL:
          type: integer
          nullable: true
        PROD_ZEIT:
          type: number
          format: double
          nullable: true
        SOLL_PROD_ZEIT:
          type: number
          format: double
          nullable: true
        PLAN_BELEGUNGS_ZEIT:
          type: number
          format: double
          nullable: true
        RUEST_ZEIT:
          type: number
          format: double
          nullable: true
        NEBEN_ZEIT:
          type: number
          format: double
          nullable: true
        STOER_ZEIT:
          type: number
          format: double
          nullable: true
        QTY_GUT:
          type: number
          format: double
          nullable: true
        QTY_AUS:
          type: number
          format: double
          nullable: true
        QTY_BEAN:
          type: number
          format: double
          nullable: true
        QTY_NACH:
          type: number
          format: double
          nullable: true
    # Basic-Properties      
    source:
      type: object
      properties:
        version:
          type: string
        connector:
          type: string
        name:
          type: string
        ts_ms:
          type: integer
          format: int64
        snapshot:
          type: string
        db:
          type: string
        sequence:
          type: string
          format: nullable
        schema:
          type: string
        table:
          type: string
        change_lsn:
          type: string
        commit_lsn:
          type: string
        event_serial_no:
          type: integer
          format: int32
    op:
      type: string
      enum:
        - 'c'
        - 'd'
        - 'u'
    ts_ms:
      type: integer
      format: int64
    transaction:
      type: string
      nullable: true