name: configuration-service

on:
  push:
    paths:
      - 'configuration-service/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generate-controllers:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: create controller-out dir
        run: |
          mkdir out
          cd out 
          mkdir controller
          
      - name: generate C# controller
        uses: docker://openapitools/openapi-generator-cli
        with:
          args: generate -o /github/out/controller -i /github/workspace/configuration-service/v1/configuration-service-v1.yaml -g aspnetcore -o /out --additional-properties aspnetCoreVersion=5.0,buildTarget=library,operationModifier=abstract,packageName=PAG.Mes.ConfigurationService.ControllerStub
          
