name: proxia-mes_comu-db_TRS_RES_change-event_v1

on:
  push:
    paths:
      - 'topics/comu-db_TRS_RES_change/v1/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  READ_PROXIA_GITHUB_PACKAGES_SECRET: ${{ secrets.READ_PROXIA_GITHUB_PACKAGES_SECRET }}
  READ_PROXIA_GITHUB_PACKAGES_USER: flobuc
  GEN_OUT_DIR: gen
  INTERFACE_FILE: topics/comu-db_TRS_RES_change/v1/proxia-mes_comu-db_TRS_RES_change-event_v1.yaml
  GITHUB_NUGET_REPOSITORY: https://nuget.pkg.github.com/proxia-mes/index.json
  GIT_TAG_NAME: proxia-mes_comu-db_TRS_RES_change-event_v1_v
  PACKAGE_NAME: PAG.Mes.MonitoringDashboard.ComuDbTrsResChangeEvent
  PROJECT_DIR: gen/src/PAG.Mes.MonitoringDashboard.ComuDbTrsResChangeEvent

jobs:
  generate-csharp-client:
    runs-on: ubuntu-20.04

    steps:
      - name: Checks-out interfaces repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Create generator output directory
        run: mkdir -p $GEN_OUT_DIR
        
      - name: Get interface version from OpenAPI Spec yaml and set to env
        run: echo INTERFACE_VERSION=`yq eval .info.version $INTERFACE_FILE` >> $GITHUB_ENV

      - name: Generate C# client code
        uses: docker://openapitools/openapi-generator-cli:v5.3.0
        with:
          args: generate -o /github/workspace/${{env.GEN_OUT_DIR}} -i /github/workspace/${{env.INTERFACE_FILE}} -g csharp-netcore --additional-properties targetFramework=net5.0,packageName=${{env.PACKAGE_NAME}},packageVersion=${{env.INTERFACE_VERSION}}
      
      - name: Change access rights for generated sources
        run: |
             sudo chmod 777 -R $GEN_OUT_DIR
             ls -la $GEN_OUT_DIR
      
      - name: Replace RepositoryUrl in csproj-File (necessary for nuget push to GitHub) 
        run: sed -i "s|GIT_USER_ID/GIT_REPO_ID|$GITHUB_REPOSITORY|" $PROJECT_DIR/$PACKAGE_NAME.csproj
            
      - name: Add GitHub Nuget Source
        run: dotnet nuget add source --username $READ_PROXIA_GITHUB_PACKAGES_USER --password $READ_PROXIA_GITHUB_PACKAGES_SECRET --store-password-in-clear-text --name github "$GITHUB_NUGET_REPOSITORY"
            
      - name: Install dependencies
        run: dotnet restore $PROJECT_DIR
      
      - name: Build
        run: dotnet build --configuration Release --no-restore $PROJECT_DIR/
            
      - name: Create the Nuget package
        run: dotnet pack $PROJECT_DIR/$PACKAGE_NAME.csproj --no-build --configuration Release
      
      - name: Publish the Nuget package to Github Package Repository (GPR)
        run: dotnet nuget push $PROJECT_DIR/bin/Release/$PACKAGE_NAME*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github

      - name: Tag commit with interface version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GIT_TAG_NAME }}${{env.INTERFACE_VERSION}}